// This file is being included by "base/plugins.cpp"
#if PLUGIN_ENABLED_STATIC(GRIM)
LINK_PLUGIN(GRIM)
#endif
#if PLUGIN_ENABLED_STATIC(MYST3)
LINK_PLUGIN(MYST3)
#endif
#if PLUGIN_ENABLED_STATIC(TINSEL)
LINK_PLUGIN(TINSEL)
#endif
